job_id: tree-pruner-da326b0e-84f0-45c9-9b0d-2a6be5e786e1
email: jojoskilee@gmail.com
tree_base: mammaltree
tree_set: MamPhy_BDvr_Completed_5911sp_topoCons_NDexp
sample_size: 100
names: [Abrawayaomys chebezi, Rhinolophus rex]
sample_trees: [MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4743.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3246.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4915.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0402.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5134.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6692.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1174.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3445.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2323.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6774.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7082.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1386.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8246.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6722.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2243.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1720.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4947.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1171.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7325.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0952.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6725.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3092.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8309.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4100.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2430.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1029.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6880.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9625.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8689.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5620.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9556.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7882.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2032.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1278.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3765.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6485.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9134.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9340.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7584.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8538.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8927.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8199.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8964.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2895.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2255.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2907.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3456.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9274.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2874.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0962.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2627.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0248.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5636.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1711.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8806.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7808.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9778.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9813.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4862.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8064.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4681.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3701.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2834.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4570.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1404.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7394.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8984.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7762.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2357.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5438.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5916.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9282.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0786.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1408.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6150.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2405.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0886.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2005.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7235.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4965.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5758.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4231.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5807.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1225.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4863.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4396.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0972.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4186.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0997.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3724.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6439.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7563.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5806.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5427.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5978.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7633.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5261.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7797.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6929.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3924.tre]
status: CREATED
created_at: "2025-06-26T13:23:17Z"
completed_at: ""
bad_names: {}
